name: 'Check Compatibility'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # See: https://github.com/KohlbacherLab/dnpm-dip-api-gateway/blob/main/app/controllers/README.md#synthetic-json-data
    - name: Download synthetic mtb patient record
      run: curl -f -L https://dnpm-dip.net/api/mtb/fake/data/patient-record -o ./tests/mv64e-mtb-fake-patient.json
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
